### ISSUE TITLE
Vintage

### ISSUE THREAD

**Issue by martmwangi** [Specro/Philter#3]
Hi, everything works fine except for the custom vintage philters, do I need to link anything else to use them?

**Comment by Specro** [comment]
Hi,
make sure to declare the path to the philter.min.js file when you initialize the plugin. If philter.min.js is in `js/philter` directory, write it like this `new Philter({ url: 'js/philter' });`.
Also custom SVG filters don't work without a server since XHR requests to the file system are denied by the browser. If you're developing locally you'll have to setup a gulp or grunt srever or an AMP stack. Check your browser console. Do you get any warnings or errors?

**Comment by martmwangi** [comment]
Hi, I`ll first set up a  grunt server, are color philters also part of custom SVG filters?

**Comment by Specro** [comment]
Yes, they are. oh, I also forgot to mention that you need the svg folder in your philter.min.js directory, cause that's where the filters are being loaded from (will add this to readme).

**Comment by Specro** [comment]
Have you solved your issue?
