### ISSUE TITLE
Loading as module

### ISSUE THREAD

**Issue by S1SYPHOS** [Specro/Philter#5]
Hey there,
what's the recommended way of consuming Philter as module? Tried the usual `require()`, `import` etc, but ended up with pasting it directly into my `.js` file ..

Cheers!

**Comment by Specro** [comment]
Currently Philter doesn't support any module method, it just attaches itself to the window global. I would write a quick UMD implementation but with the university and all I don't really have much time to do this. If you or anyone else wants to make a pull request for this I'd approve it. Otherwise I work on this plugin more often during the summer or holidays.
